# Generated by Django 4.0.6 on 2023-08-11 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('num_visit', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('token', models.CharField(blank=True, max_length=20, null=True)),
                ('date_registration', models.DateField(auto_now=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
        ),
    ]
