# Generated by Django 4.0.6 on 2023-08-11 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='Department',
            new_name='department',
        ),
    ]
