# Generated by Django 4.0.6 on 2023-08-11 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('num_department', models.BigAutoField(primary_key=True, serialize=False)),
                ('floor', models.PositiveSmallIntegerField(choices=[(1, 'Primer piso'), (2, 'Segundo piso'), (3, 'Tercer piso')])),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
